version: '3.9'
services:
  backend:
    build: .
    volumes:
      - .:/config
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres
    volumes:
      - .dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - .pgadmin4_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@a.com
      PGADMIN_DEFAULT_PASSWORD: pass

  redis:
    image: redis
    container_name: redis_test #コマンド時に使用するコンテナ名
    ports:
      - 6379:6379 #redisのデフォルトのポートは6379

volumes:
    postgres_data:
    pgadmin4_data: