# Generated by Django 3.1.7 on 2022-11-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
